//go:build windows

// Code generated by goinvoke invoker; DO NOT EDIT.
// Documentation: https://pkg.go.dev/github.com/jamesits/goinvoke
// Full command line: `"invoker" "-dll" "virtdisk.dll" "-generate"`
//go:generate "invoker" "-dll" "virtdisk.dll" "-generate"

package virtdisk

import (
	"github.com/jamesits/goinvoke"
	"golang.org/x/sys/windows"
)

// Virtdisk contains all exports from "virtdisk.dll".
type Virtdisk struct {
	AddVirtualDiskParent                   *windows.Proc `func:"AddVirtualDiskParent"`
	ApplySnapshotVhdSet                    *windows.Proc `func:"ApplySnapshotVhdSet"`
	AttachVirtualDisk                      *windows.Proc `func:"AttachVirtualDisk"`
	BreakMirrorVirtualDisk                 *windows.Proc `func:"BreakMirrorVirtualDisk"`
	CompactVirtualDisk                     *windows.Proc `func:"CompactVirtualDisk"`
	CompleteForkVirtualDisk                *windows.Proc `func:"CompleteForkVirtualDisk"`
	CreateVirtualDisk                      *windows.Proc `func:"CreateVirtualDisk"`
	DeleteSnapshotVhdSet                   *windows.Proc `func:"DeleteSnapshotVhdSet"`
	DeleteVirtualDiskMetadata              *windows.Proc `func:"DeleteVirtualDiskMetadata"`
	DetachVirtualDisk                      *windows.Proc `func:"DetachVirtualDisk"`
	EnumerateVirtualDiskMetadata           *windows.Proc `func:"EnumerateVirtualDiskMetadata"`
	ExpandVirtualDisk                      *windows.Proc `func:"ExpandVirtualDisk"`
	ForkVirtualDisk                        *windows.Proc `func:"ForkVirtualDisk"`
	GetAllAttachedVirtualDiskPhysicalPaths *windows.Proc `func:"GetAllAttachedVirtualDiskPhysicalPaths"`
	GetStorageDependencyInformation        *windows.Proc `func:"GetStorageDependencyInformation"`
	GetVirtualDiskInformation              *windows.Proc `func:"GetVirtualDiskInformation"`
	GetVirtualDiskMetadata                 *windows.Proc `func:"GetVirtualDiskMetadata"`
	GetVirtualDiskOperationProgress        *windows.Proc `func:"GetVirtualDiskOperationProgress"`
	GetVirtualDiskPhysicalPath             *windows.Proc `func:"GetVirtualDiskPhysicalPath"`
	MergeVirtualDisk                       *windows.Proc `func:"MergeVirtualDisk"`
	MirrorVirtualDisk                      *windows.Proc `func:"MirrorVirtualDisk"`
	ModifyVhdSet                           *windows.Proc `func:"ModifyVhdSet"`
	OpenVirtualDisk                        *windows.Proc `func:"OpenVirtualDisk"`
	QueryChangesVirtualDisk                *windows.Proc `func:"QueryChangesVirtualDisk"`
	RawSCSIVirtualDisk                     *windows.Proc `func:"RawSCSIVirtualDisk"`
	ResizeVirtualDisk                      *windows.Proc `func:"ResizeVirtualDisk"`
	SetVirtualDiskInformation              *windows.Proc `func:"SetVirtualDiskInformation"`
	SetVirtualDiskMetadata                 *windows.Proc `func:"SetVirtualDiskMetadata"`
	TakeSnapshotVhdSet                     *windows.Proc `func:"TakeSnapshotVhdSet"`
}

// Unmarshal loads the corresponding DLL into memory and fills export functions defined in the struct.
func (dll *Virtdisk) Unmarshal(path string) error {
	return goinvoke.Unmarshal(path, dll)
}
